# Generated by Django 4.0.4 on 2022-04-27 06:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_summary', models.TextField()),
                ('post_body', tinymce.models.HTMLField()),
            ],
        ),
    ]
