# Generated by Django 4.0.4 on 2022-05-12 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0005_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField()),
                ('comment', models.TextField(max_length=500)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.postmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='comments',
        ),
        migrations.AlterField(
            model_name='create_account',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
