# Generated by Django 4.0.4 on 2022-05-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_commentmodel_delete_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='comment',
        ),
    ]
