# Generated by Django 4.0.4 on 2022-05-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_remove_commentmodel_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='create_account',
        ),
    ]
