# Generated by Django 4.0.4 on 2022-05-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_delete_create_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32)),
                ('Email', models.CharField(max_length=320)),
                ('Mobile_Number', models.CharField(max_length=12)),
                ('Query', models.TextField(max_length=150)),
                ('Added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
